version: '3.8'

networks:
  webdev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-wtt
    ports:
      - 8000:80
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webdev

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-wtt
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/project
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - webdev

  mysql:
    image: mariadb
    container_name: mysql-wtt
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wtt
      MYSQL_USER: wtt
      MYSQL_PASSWORD: wtt
    ports:
      - 4306:3306
    expose:
      - 3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - webdev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-wtt
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - webdev

  maildev:
    image: maildev/maildev
    container_name: maildev-wtt
    ports:
      - 1080:80
    networks:
      - webdev
